Repository adoptium/api.adoptium.net, pull requests merged in 2021-04, with the labels that each got.

#10 Add proposed rework of update mechanism
  docs/adr/0006-update-rework.md
Labels: enhancement

#7 Add ADR to update paging
  docs/adr/0005-update-paging.md
Labels: documentation, enhancement

#11 Add update notification adr
  docs/adr/0007-update-notification.md
Labels: enhancement

#8 Update to Quarkus 1.13
  .github/dependabot.yml
  .github/workflows/build.yml
  .s2i/bin/assemble
  Dockerfile
  adoptopenjdk-api-v3-frontend/pom.xml
  adoptopenjdk-api-v3-frontend/src/main/docker/Dockerfile.jvm
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/JsonSerialiserConfig.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/JsonSerializerConfig.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
  adoptopenjdk-api-v3-frontend/src/test/kotlin/net/adoptopenjdk/api/V3Test.kt
  pom.xml
Labels: enhancement

#20 Feature/resteasy reactive
  adoptopenjdk-api-v3-frontend/pom.xml
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/V3.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/DayMeter.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/metrics/StatsInterceptor.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/AssetsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/V1Route.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/VersionResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/AvailableReleasesResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/PlatformsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/ReleaseListResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/info/VariantsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/BinaryResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/packages/InstallerResource.kt
  adoptopenjdk-api-v3-frontend/src/main/kotlin/net/adoptopenjdk/api/v3/routes/stats/DownloadStatsResource.kt
  adoptopenjdk-api-v3-frontend/src/main/resources/application.properties
  pom.xml
Labels: bug

#33 Update kmongo to 4.2, coroutine to 1.4 and other dependencies
  adoptopenjdk-api-v3-frontend/pom.xml
  adoptopenjdk-api-v3-persistence/pom.xml
  adoptopenjdk-api-v3-updater/pom.xml
  pom.xml
Labels: dependencies
